/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LoginForm {}
}

declare global {


  interface HTMLLoginFormElement extends Components.LoginForm, HTMLStencilElement {}
  var HTMLLoginFormElement: {
    prototype: HTMLLoginFormElement;
    new (): HTMLLoginFormElement;
  };
  interface HTMLElementTagNameMap {
    'login-form': HTMLLoginFormElement;
  }
}

declare namespace LocalJSX {
  interface LoginForm {
    'onFormSubmit'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'login-form': LoginForm;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'login-form': LocalJSX.LoginForm & JSXBase.HTMLAttributes<HTMLLoginFormElement>;
    }
  }
}


